language: c

env: PATH="$HOME/.local/bin:$PATH"

addons:
  apt:
    packages:
      - libgtk-3-dev
      - python3-pip

install:
  - pip3 install --user meson
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - mv ninja $HOME/.local/bin/

script:
  - meson builddir
  - cd builddir
  - ninja

